services:
  packing-app:
    build: .
    container_name: packing_app
    ports:
      - "5038:5000"
    volumes:
      - ./data:/app/data  # Maps the DB file to your NAS storage
      - .:/app
    restart: unless-stopped
